# -*- Python -*-

import os

Import('env')
env = env.Clone()

rpath_install = env.Literal(os.path.join('\\$$ORIGIN', '..', 'lib'))
rpath_build = env.Literal(os.path.join('\\$$ORIGIN', '..', 'libs'))

env.SetDefault(RPATH_INSTALL=rpath_install)
env.SetDefault(RPATH_BUILD=rpath_build)
rpath = [env['RPATH_INSTALL'], env['RPATH_BUILD']]
rpath_link = [f'-Wl,-rpath-link={env["RPATH_BUILD"]}']
env.AppendUnique(LINKFLAGS = ['-z', 'origin', rpath_link])
env.AppendUnique(RPATH = rpath)
env.AppendUnique(LIBPATH = ['../libs'])

env.SConscript('libs/SConscript', exports='env')
env.SConscript('bins/SConscript', exports='env')
